volumes:
  mongo-data-prod:

networks:
  portfolio-network-prod:
    driver: bridge

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-prod
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-prod:/data/db
    networks:
      - portfolio-network-prod

  backend:
    container_name: portfolio-backend
    image: naeemkhan14/portfolio-backend:latest
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - /mnt/user/appdata/portfolio-v3/media:/app/media
    ports:
    - '127.0.0.1:3001:3001'
    - '10.253.0.1:4001:3001'
    networks:
      - portfolio-network-prod

  frontend:
    container_name: portfolio-frontend
    image: naeemkhan14/portfolio-frontend:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - backend
    networks:
      - portfolio-network-prod

  nginx:
    image: nginx:stable
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - '8888:80'
    volumes:
      - /mnt/user/appdata/portfolio-v3/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/user/appdata/portfolio-v3/media:/app/media:ro
      - /mnt/user/appdata/portfolio-v3/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network-prod
