services:
  mongo:
    image: mongo:8.0
    container_name: mongo-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    container_name: portfolio-v3-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - mongo

volumes:
  mongo-data: