services:
  mongo:
    image: mongo:8.0
    container_name: mongo-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./Application/Backend
      dockerfile: Dockerfile-dev
    container_name: payload-backend-dev
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    env_file:
      - ./Application/Backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./Application/Backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./Application/Frontend
      dockerfile: Dockerfile-dev
    container_name: nextjs-frontend-dev
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./Application/Frontend/.env.local
    volumes:
      - ./Application/Frontend:/app
      - /app/node_modules

volumes:
  mongo-data: