services:
  db:
    image: postgres:17
    container_name: blog_postgres_dev
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: portfolio-v3-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: sh -c "npx prisma studio --hostname 0.0.0.0 --port 5555 & npm run dev"
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  pgdata: