services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend
    image: naeemkhan14/portfolio-frontend:latest
    env_file: .env
    depends_on:
      - payload
    networks:
      - portfolio_net
    ports:
      - "3501:80"

  payload:
    build:
      context: .
      dockerfile: Dockerfile.payload
    container_name: portfolio-cms
    env_file: .env
    volumes:
      - /mnt/user/appdata/portfolio-v3/media:/app/media
    networks:
      - portfolio_net
    expose:
      - 3001 
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    networks:
      - portfolio_net
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"

  nginx:
    image: nginx:stable-alpine
    container_name: portfolio-nginx
    depends_on:
      - frontend
      - payload
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/user/appdata/portfolio-v3/logs:/var/log/nginx
      - /mnt/user/appdata/portfolio-v3/media:/app/media:ro
    networks:
      - portfolio_net
    restart: unless-stopped

networks:
  portfolio_net:
    driver: bridge

volumes:
  mongo-data: