services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: naeemkhan14/portfolio-v3:latest
    container_name: portfolio-v3
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
