volumes:
  mongo-data:

networks:
  portfolio-network:
    driver: bridge

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-dev
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - portfolio-network

  backend:
    build:
      context: ../../
      dockerfile: Docker/Dev/Dockerfile-dev
    container_name: payload-backend-dev
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ../../:/app
      - /app/node_modules
    networks:
      - portfolio-network


