FROM node:22.17-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./package.json ./package-lock.json* ./yarn.lock* ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose frontend dev port
EXPOSE 3501

# Start Next.js dev server
CMD ["npm", "run", "dev"]