services:
  frontend:
    build:
      context: ../../
      dockerfile: Docker/Dev/Dockerfile-dev
    container_name: nextjs-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ../../:/app
      - /app/node_modules
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
