# To use this Dockerfile, you have to set `output: 'standalone'` in your next.config.mjs file.
# From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

FROM node:22.17-alpine
# Set working directory
WORKDIR /app

# Install dependencies
COPY ./package.json ./package-lock.json* ./yarn.lock* ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose Payload dev server port
EXPOSE 3001

# Start Payload dev server
CMD ["npm", "run", "dev"]