services:
  frontend:
    container_name: portfolio-frontend
    image: naeemkhan14/portfolio-frontend:latest
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: Docker/Prod/Dockerfile-prod
      args:
        CMS_INTERNAL_URL: ${CMS_INTERNAL_URL}
    restart: always
    ports:
      - 3501:3501
    networks:
      - portfolio-network-prod

networks:
  portfolio-network-prod:
    driver: bridge
